spring:
  web:
    resources:
      static-locations: classpath:/static/
  datasource:
    url: jdbc:mysql://localhost:3306/artificial_train?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: GJSE8YqDww
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jerry86189.springbootvuedemo.entity

logging:
  level:
    org:
      springframework:
        web: DEBUG

server:
  port: 8888


